site_name: dovwms
repo_url: https://github.com/zawadzkim/dovwms
site_url: https://zawadzkim.github.io/dovwms
site_description: Simple client for DOV WMS services.
site_author: Mateusz Zawadzki
edit_uri: edit/main/docs/
repo_name: zawadzkim/dovwms
copyright: Maintained by <a href="https://zawadzkim.com">Mateusz Zawadzki</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - autorefs
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths: [..] # This tells mkdocstrings to look in the parent directory
          options:
            show_submodules: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_toc_entry: false
            show_root_heading: false
            heading_level: 2
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zawadzkim/dovwms
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/dovwms

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
