name: Release

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "docs/**"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release:
    uses: zawadzkim/shared-gh-workflows/.github/workflows/python-release.yml@main
