name: Release

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "docs/**"

jobs:
  release:
    uses: zawadzkim/shared-gh-workflows/.github/workflows/python-release.yml@main