name: Tests

on:
  push:
    branches:
      - main
      - master
      - dev
    paths:
      - "dovwms/**"
      - "tests/**"
      - "pyproject.toml"
      - "poetry.lock"
  pull_request:
    paths:
      - "dovwms/**"
      - "tests/**"
      - "pyproject.toml"
      - "poetry.lock"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Run tests
        run: |
          poetry run pytest --cov=dovwms --cov-report=xml -m "not integration"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
